<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLhNrfDQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLhNrfDQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLhNrfDQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLhNrfDQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLhNrfDQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'LhNrfDQ',
    'container.build_id' => 'fce89921',
    'container.build_time' => 1584628749,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLhNrfDQ');
