<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCwboryl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCwboryl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCwboryl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCwboryl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCwboryl\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cwboryl',
    'container.build_id' => 'c719f86a',
    'container.build_time' => 1586618977,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCwboryl');
