<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIAutlaQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIAutlaQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIAutlaQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIAutlaQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIAutlaQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'IAutlaQ',
    'container.build_id' => 'c56f817a',
    'container.build_time' => 1586188881,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIAutlaQ');
